#!/usr/bin/env python3
"""
05_prepare_model_data.py

Prepara os dados para modelação:
- separa X e y
- remove colunas que não devem ser usadas como predictors
- aplica one-hot encoding a variáveis categóricas
- faz train/test split
- aplica normalização para Logistic Regression

Exemplo:
python 05_prepare_model_data.py --input outputs/dataset_A_causality_likely_contacts_train_v3_with_features.csv
"""

import argparse
from pathlib import Path
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import joblib

DROP_COLUMNS = ["contact_id", "customer_id", "contact_datetime", "first_response_datetime"]
TARGET = "converted"

CATEGORICAL_COLUMNS = [
    "contact_source_type", "customer_type", "product_id", "product_category",
    "product_subcategory", "product_collection",
]

NUMERIC_COLUMNS = [
    "response_time_min", "is_payday_period", "is_peak_season", "month",
    "day_of_month", "day_of_week", "hour_of_day", "fast_response_24h",
]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="CSV generated by 04_create_features.py")
    parser.add_argument("--output-dir", default="outputs/model_ready", help="Directory for model-ready outputs")
    parser.add_argument("--test-size", type=float, default=0.2, help="Test size proportion")
    parser.add_argument("--random-state", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(args.input)
    print("\n=== 05. PREPARE MODEL DATA ===\n")
    print(f"Input rows: {len(df)}")

    missing_required = [col for col in [TARGET] + NUMERIC_COLUMNS + CATEGORICAL_COLUMNS if col not in df.columns]
    if missing_required:
        raise ValueError(f"Missing required columns: {missing_required}")

    y = df[TARGET].astype(int)
    X_raw = df.drop(columns=[TARGET] + [col for col in DROP_COLUMNS if col in df.columns])

    model_columns = NUMERIC_COLUMNS + CATEGORICAL_COLUMNS
    X_raw = X_raw[model_columns]

    X_encoded = pd.get_dummies(X_raw, columns=CATEGORICAL_COLUMNS, drop_first=False, dtype=int)

    X_train, X_test, y_train, y_test = train_test_split(
        X_encoded, y, test_size=args.test_size, random_state=args.random_state, stratify=y
    )

    scaler = StandardScaler()
    X_train_scaled = X_train.copy()
    X_test_scaled = X_test.copy()
    X_train_scaled[X_train.columns] = scaler.fit_transform(X_train)
    X_test_scaled[X_test.columns] = scaler.transform(X_test)

    X_train.to_csv(output_dir / "X_train.csv", index=False)
    X_test.to_csv(output_dir / "X_test.csv", index=False)
    y_train.to_csv(output_dir / "y_train.csv", index=False)
    y_test.to_csv(output_dir / "y_test.csv", index=False)
    X_train_scaled.to_csv(output_dir / "X_train_scaled_for_logistic_regression.csv", index=False)
    X_test_scaled.to_csv(output_dir / "X_test_scaled_for_logistic_regression.csv", index=False)
    joblib.dump(scaler, output_dir / "standard_scaler.joblib")
    pd.DataFrame({"feature": X_encoded.columns}).to_csv(output_dir / "feature_names.csv", index=False)

    print(f"X shape after one-hot encoding: {X_encoded.shape}")
    print(f"Train rows: {len(X_train)}")
    print(f"Test rows: {len(X_test)}")
    print(f"Conversion rate in train: {y_train.mean() * 100:.1f}%")
    print(f"Conversion rate in test: {y_test.mean() * 100:.1f}%")
    print(f"\nSaved model-ready files to: {output_dir}")
    print("\n✅ Model data preparation completed.")


if __name__ == "__main__":
    main()
